/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GamePackage;

import java.net.URL;


/**
 *
 * @author ASUS
 */
public class FormInstructionPage extends javax.swing.JFrame {

    /**
     * Creates new form FormInstructionPage
     */
    ClassSound sound = new ClassSound();    
    URL soundbgURL = getClass().getResource("bgplay.wav");
    URL soundbtnclickURL = getClass().getResource("button-click.wav");
    public FormInstructionPage() {
        initComponents();
        sound.setFile(soundbgURL);
        sound.play(soundbgURL);
        sound.loop(soundbgURL);
    }
    
    public void buttonclicksound(URL url){
        sound.setFile(url);
        sound.play(url);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblInstructios = new javax.swing.JLabel();
        lblmickey = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblins1 = new javax.swing.JLabel();
        lblins2 = new javax.swing.JLabel();
        lblins3 = new javax.swing.JLabel();
        lblins4 = new javax.swing.JLabel();
        lblins5 = new javax.swing.JLabel();
        lblins6 = new javax.swing.JLabel();
        lblins7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnplay = new GamePackage.ClassButtonGradient();
        btnscoretable = new GamePackage.ClassButtonGradient();
        btnexit = new GamePackage.ClassButtonGradient();
        jPanel5 = new javax.swing.JPanel();
        btnsound = new GamePackage.ClassButtonGradient();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(598, 557));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInstructios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/Instructions.png"))); // NOI18N
        jPanel2.add(lblInstructios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 210, 60));

        lblmickey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/MickeyIns.png"))); // NOI18N
        jPanel2.add(lblmickey, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 120));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255,100));

        lblins1.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblins1.setText("<html><body style='width: 245px'>1.\tThe game is played on a grid of squares.</body></html>");
        jPanel4.add(lblins1);

        lblins2.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblins2.setText("<html><body style='width: 245px'>2.\tEach square contains a number.</body></html>");
        jPanel4.add(lblins2);

        lblins3.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblins3.setText("<html><body style='width: 245px'>3.\tThe goal of the game is to rearrange <br>     the tiles like the below  image so that <br>     the grid is in numerical order, starting<br> from the top left corner and working <br> your way down each row.</body></html>");
        jPanel4.add(lblins3);

        lblins4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/arrangedpuzzle.png"))); // NOI18N
        lblins4.setText("\n");
        jPanel4.add(lblins4);

        lblins5.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblins5.setText("<html><body style='width: 245px'>4.\tYou can move the tiles by clicking on them. The tile will slide to the empty <br>space next to it.</body></html>");
        jPanel4.add(lblins5);

        lblins6.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblins6.setText("<html><body style='width: 245px'>5.\tOnly one tile can be moved at a time.</body></html>");
        jPanel4.add(lblins6);

        lblins7.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblins7.setText("<html><body style='width: 245px'>6.\tYou have one hour to solve the puzzle.</body></html>");
        jPanel4.add(lblins7);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 330, 430));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/new.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 560));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 590));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255,100));

        btnplay.setText("Play");
        btnplay.setColor1(new java.awt.Color(0, 0, 0));
        btnplay.setColor2(new java.awt.Color(51, 51, 255));
        btnplay.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnplay.setMaximumSize(new java.awt.Dimension(75, 42));
        btnplay.setMinimumSize(new java.awt.Dimension(75, 42));
        btnplay.setPreferredSize(new java.awt.Dimension(149, 42));
        btnplay.setSizeSpeed(5.0F);
        btnplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplayActionPerformed(evt);
            }
        });
        jPanel3.add(btnplay);

        btnscoretable.setText("Score Table");
        btnscoretable.setColor1(new java.awt.Color(0, 0, 0));
        btnscoretable.setColor2(new java.awt.Color(255, 255, 51));
        btnscoretable.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnscoretable.setSizeSpeed(5.0F);
        btnscoretable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnscoretableActionPerformed(evt);
            }
        });
        jPanel3.add(btnscoretable);

        btnexit.setText("Exit");
        btnexit.setColor1(new java.awt.Color(0, 0, 0));
        btnexit.setColor2(new java.awt.Color(255, 0, 51));
        btnexit.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnexit.setPreferredSize(new java.awt.Dimension(149, 42));
        btnexit.setSizeSpeed(5.0F);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel3.add(btnexit);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsound.setForeground(new java.awt.Color(0, 0, 0));
        btnsound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/Sound.png"))); // NOI18N
        btnsound.setColor1(new java.awt.Color(204, 204, 255));
        btnsound.setColor2(new java.awt.Color(0, 204, 102));
        btnsound.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnsound.setSizeSpeed(5.0F);
        jPanel5.add(btnsound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel5.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 220, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/logingMickey.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 290, 320));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/new.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 270, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        buttonclicksound(soundbtnclickURL);
        FormExitPage ef = new FormExitPage();
        ef.setVisible(true);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplayActionPerformed
        FormUserLoginPage udf = new FormUserLoginPage();
        udf.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnplayActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        jSlider1.setMinimum(-40);
        jSlider1.setMaximum(6);
        sound.currentVolume = jSlider1.getValue();
        if(sound.currentVolume == -40){
            sound.currentVolume = -80;
        }
        sound.fc.setValue(sound.currentVolume);
    }//GEN-LAST:event_jSlider1StateChanged

    private void btnscoretableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnscoretableActionPerformed
        this.toBack();
        FormScoreTablePage sctf = new FormScoreTablePage();
        sctf.setVisible(true);
        sctf.toFront();
    }//GEN-LAST:event_btnscoretableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInstructionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInstructionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInstructionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInstructionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInstructionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GamePackage.ClassButtonGradient btnexit;
    private GamePackage.ClassButtonGradient btnplay;
    private GamePackage.ClassButtonGradient btnscoretable;
    private GamePackage.ClassButtonGradient btnsound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblInstructios;
    private javax.swing.JLabel lblins1;
    private javax.swing.JLabel lblins2;
    private javax.swing.JLabel lblins3;
    private javax.swing.JLabel lblins4;
    private javax.swing.JLabel lblins5;
    private javax.swing.JLabel lblins6;
    private javax.swing.JLabel lblins7;
    private javax.swing.JLabel lblmickey;
    // End of variables declaration//GEN-END:variables
}
