/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GamePackage;

import java.net.URL;


/**
 *
 * @author ASUS
 */
public class FormExitPage extends javax.swing.JFrame {

    ClassSound sound = new ClassSound();
    URL soundbtnclickURL = getClass().getResource("button-click.wav");
    public FormExitPage() {
        initComponents();
    }

    public void buttonclicksound(URL url){
        sound.setFile(url);
        sound.play(url);        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnyes = new GamePackage.ClassButtonGradient();
        btnno = new GamePackage.ClassButtonGradient();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnyes.setForeground(new java.awt.Color(0, 0, 0));
        btnyes.setText("Yes");
        btnyes.setColor1(new java.awt.Color(153, 153, 153));
        btnyes.setColor2(new java.awt.Color(153, 204, 255));
        btnyes.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnyes.setSizeSpeed(5.0F);
        btnyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyesActionPerformed(evt);
            }
        });
        jPanel1.add(btnyes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));

        btnno.setForeground(new java.awt.Color(0, 0, 0));
        btnno.setText("No");
        btnno.setColor1(new java.awt.Color(153, 153, 153));
        btnno.setColor2(new java.awt.Color(153, 204, 255));
        btnno.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnno.setMaximumSize(new java.awt.Dimension(73, 42));
        btnno.setMinimumSize(new java.awt.Dimension(73, 42));
        btnno.setPreferredSize(new java.awt.Dimension(73, 42));
        btnno.setSizeSpeed(5.0F);
        btnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 70, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/Mickey2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 100, 150));

        jLabel2.setFont(new java.awt.Font("Poor Richard", 3, 24)); // NOI18N
        jLabel2.setText("Do you reallay want to exit?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/new.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyesActionPerformed
        buttonclicksound(soundbtnclickURL);
        System.exit(0);
    }//GEN-LAST:event_btnyesActionPerformed

    private void btnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoActionPerformed
        buttonclicksound(soundbtnclickURL);
        this.toBack();
        this.setVisible(false);
    }//GEN-LAST:event_btnnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormExitPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormExitPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormExitPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormExitPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormExitPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GamePackage.ClassButtonGradient btnno;
    private GamePackage.ClassButtonGradient btnyes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
