/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GamePackage;

import DataBaseConnections.CrudUtil;
import java.net.URL;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author ASUS
 */
public class FormScoreTablePage extends javax.swing.JFrame {

    /**
     * Creates new form FormScoreTablePage
     */
    ClassSound sound = new ClassSound();
    URL soundbtnclickURL = getClass().getResource("button-click.wav");
    public FormScoreTablePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlplay = new javax.swing.JPanel();
        lblPlace = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblMoves = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        pnlplay1 = new javax.swing.JPanel();
        lblPlace1 = new javax.swing.JLabel();
        lblPlayer1 = new javax.swing.JLabel();
        lblMoves1 = new javax.swing.JLabel();
        lblTime1 = new javax.swing.JLabel();
        pnlplay2 = new javax.swing.JPanel();
        lblPlace2 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        lblMoves2 = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        pnlplay3 = new javax.swing.JPanel();
        lblPlace3 = new javax.swing.JLabel();
        lblPlayer3 = new javax.swing.JLabel();
        lblMoves3 = new javax.swing.JLabel();
        lblTime3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new GamePackage.ClassButtonGradient();
        btnRefresh = new GamePackage.ClassButtonGradient();
        lblbg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,100));

        pnlplay.setBackground(new java.awt.Color(153, 204, 255));

        lblPlace.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblPlace.setText("Place");
        lblPlace.setPreferredSize(new java.awt.Dimension(60, 22));
        pnlplay.add(lblPlace);

        lblPlayer.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblPlayer.setText("Player");
        lblPlayer.setPreferredSize(new java.awt.Dimension(150, 22));
        pnlplay.add(lblPlayer);

        lblMoves.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblMoves.setText("Moves");
        lblMoves.setPreferredSize(new java.awt.Dimension(65, 22));
        pnlplay.add(lblMoves);

        lblTime.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTime.setText("Time");
        lblTime.setPreferredSize(new java.awt.Dimension(50, 22));
        pnlplay.add(lblTime);

        jPanel2.add(pnlplay);

        pnlplay1.setBackground(new java.awt.Color(255, 255, 255));

        lblPlace1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblPlace1.setForeground(new java.awt.Color(255, 0, 51));
        lblPlace1.setText("01");
        lblPlace1.setPreferredSize(new java.awt.Dimension(60, 22));
        pnlplay1.add(lblPlace1);

        lblPlayer1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblPlayer1.setForeground(new java.awt.Color(255, 0, 51));
        lblPlayer1.setText("Player1");
        lblPlayer1.setPreferredSize(new java.awt.Dimension(150, 22));
        pnlplay1.add(lblPlayer1);

        lblMoves1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblMoves1.setForeground(new java.awt.Color(255, 0, 51));
        lblMoves1.setText("Moves1");
        lblMoves1.setPreferredSize(new java.awt.Dimension(65, 22));
        pnlplay1.add(lblMoves1);

        lblTime1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblTime1.setForeground(new java.awt.Color(255, 0, 51));
        lblTime1.setText("Time1");
        lblTime1.setPreferredSize(new java.awt.Dimension(50, 22));
        pnlplay1.add(lblTime1);

        jPanel2.add(pnlplay1);

        pnlplay2.setBackground(new java.awt.Color(255, 255, 255));

        lblPlace2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblPlace2.setForeground(new java.awt.Color(255, 204, 0));
        lblPlace2.setText("02");
        lblPlace2.setPreferredSize(new java.awt.Dimension(60, 22));
        pnlplay2.add(lblPlace2);

        lblPlayer2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblPlayer2.setForeground(new java.awt.Color(255, 204, 0));
        lblPlayer2.setText("Player2");
        lblPlayer2.setPreferredSize(new java.awt.Dimension(150, 22));
        pnlplay2.add(lblPlayer2);

        lblMoves2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblMoves2.setForeground(new java.awt.Color(255, 204, 0));
        lblMoves2.setText("Moves2");
        lblMoves2.setPreferredSize(new java.awt.Dimension(65, 22));
        pnlplay2.add(lblMoves2);

        lblTime2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblTime2.setForeground(new java.awt.Color(255, 204, 0));
        lblTime2.setText("Time2");
        lblTime2.setPreferredSize(new java.awt.Dimension(50, 22));
        pnlplay2.add(lblTime2);

        jPanel2.add(pnlplay2);

        pnlplay3.setBackground(new java.awt.Color(255, 255, 255));

        lblPlace3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblPlace3.setForeground(new java.awt.Color(0, 102, 102));
        lblPlace3.setText("03");
        lblPlace3.setPreferredSize(new java.awt.Dimension(60, 22));
        pnlplay3.add(lblPlace3);

        lblPlayer3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblPlayer3.setForeground(new java.awt.Color(0, 102, 102));
        lblPlayer3.setText("Player3");
        lblPlayer3.setPreferredSize(new java.awt.Dimension(150, 22));
        pnlplay3.add(lblPlayer3);

        lblMoves3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblMoves3.setForeground(new java.awt.Color(0, 102, 102));
        lblMoves3.setText("Moves3");
        lblMoves3.setPreferredSize(new java.awt.Dimension(65, 22));
        pnlplay3.add(lblMoves3);

        lblTime3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblTime3.setForeground(new java.awt.Color(0, 102, 102));
        lblTime3.setText("Time3");
        lblTime3.setPreferredSize(new java.awt.Dimension(50, 22));
        pnlplay3.add(lblTime3);

        jPanel2.add(pnlplay3);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 380, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/Scoretabletext.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 200, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/Scoretablemic.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 270));

        btnBack.setText("Back");
        btnBack.setColor1(new java.awt.Color(51, 153, 255));
        btnBack.setColor2(new java.awt.Color(255, 102, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnBack.setSizeSpeed(5.0F);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 100, 30));

        btnRefresh.setText("Refresh");
        btnRefresh.setColor1(new java.awt.Color(51, 153, 255));
        btnRefresh.setColor2(new java.awt.Color(255, 102, 51));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnRefresh.setSizeSpeed(5.0F);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 140, 30));

        lblbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/new.jpg"))); // NOI18N
        getContentPane().add(lblbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 290));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        sound.setFile(soundbtnclickURL);
        sound.play(soundbtnclickURL);
        this.toBack();
        this.setVisible(false);        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            String query = "SELECT Name, Moves, PlayTime FROM Players WHERE Winning_State = TRUE ORDER BY PlayTime ASC LIMIT 3";
            ResultSet result = CrudUtil.execute(query);
                    
            int playerCount = 0;
            while (result.next()) {
                playerCount++;
                String playerName = result.getString("Name");
                int moves = result.getInt("Moves");
                int playTime = result.getInt("PlayTime");
                        
                switch(playerCount){
                    case 1:
                        lblPlayer1.setText(playerName);
                        lblMoves1.setText(String.valueOf(moves));
                        lblTime1.setText(String.valueOf(playTime));
                         break;
                            case 2:
                                lblPlayer2.setText(playerName);
                                lblMoves2.setText(String.valueOf(moves));
                                lblTime2.setText(String.valueOf(playTime));
                                break;
                            case 3:
                                lblPlayer3.setText(playerName);
                                lblMoves3.setText(String.valueOf(moves));
                                lblTime3.setText(String.valueOf(playTime));
                                break;
                            default:
                                // Handle case where there are more than three players with a winning state
                                break;
                        }                                  
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "There is some issue: " + ex);
                }
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormScoreTablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormScoreTablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormScoreTablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormScoreTablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormScoreTablePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GamePackage.ClassButtonGradient btnBack;
    private GamePackage.ClassButtonGradient btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMoves;
    private javax.swing.JLabel lblMoves1;
    private javax.swing.JLabel lblMoves2;
    private javax.swing.JLabel lblMoves3;
    private javax.swing.JLabel lblPlace;
    private javax.swing.JLabel lblPlace1;
    private javax.swing.JLabel lblPlace2;
    private javax.swing.JLabel lblPlace3;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblPlayer3;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JLabel lblTime2;
    private javax.swing.JLabel lblTime3;
    private javax.swing.JLabel lblbg;
    private javax.swing.JPanel pnlplay;
    private javax.swing.JPanel pnlplay1;
    private javax.swing.JPanel pnlplay2;
    private javax.swing.JPanel pnlplay3;
    // End of variables declaration//GEN-END:variables
}
