/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GamePackage;

import java.awt.Color;
import java.net.URL;
import javax.swing.JOptionPane;



/**
 *
 * @author ASUS
 */
public class FormLoadingPage extends javax.swing.JFrame {

    /**
     * Creates new form FormLoadingPage
     */
    ClassSound sound = new ClassSound();
    URL soundbgURL = getClass().getResource("new intro.wav");
    public FormLoadingPage() {
        setUndecorated(true);
        initComponents();
        setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
        sound.setFile(soundbgURL);
        sound.play(soundbgURL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblmovingtext = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();
        lblLoadingCount = new javax.swing.JLabel();
        pgbar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(635, 520));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                WindowOpen(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/Mickey Mouse Sticker by Camp Stores - Find & Share on GIPHY.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 420, 460));

        lblmovingtext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePackage/Afunnypuzzle.png"))); // NOI18N
        getContentPane().add(lblmovingtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 480, 80));

        lblLoading.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLoading.setText("Loading...");
        getContentPane().add(lblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        lblLoadingCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLoadingCount.setText("0%");
        getContentPane().add(lblLoadingCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 40, -1));

        pgbar.setForeground(new java.awt.Color(0, 255, 51));
        pgbar.setOpaque(true);
        getContentPane().add(pgbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 480, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WindowOpen(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WindowOpen
        // Window Event - Opened:
        // Set Boundary
        final int MAX_X = 120;
        final int MIN_X = 30;
        
        Thread animation = new Thread(new Runnable(){
            @Override
            public void run() {
               int x = 20;
               int y = 30; //label start positions
               boolean checked = true;
               while(true){
                    if(checked){
                       lblmovingtext.setLocation(x, y);
                        x += 5;
                    }else{
                        lblmovingtext.setLocation(x, y);
                        x -= 5; 
                    }
                   if(x>MAX_X){
                       checked = false;
                       x = 120; //reset the X value
                   }
                   if(x<MIN_X){
                       checked = true;
                   }
                   
                   try{
                       Thread.sleep(100);
                   }catch(InterruptedException e){
                       e.printStackTrace();
                   }
               }
            }            
        });
        animation.start();
    }//GEN-LAST:event_WindowOpen

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FormLoadingPage hp = new FormLoadingPage();
        hp.setVisible(true);
        try{
            for(int i = 0; i <= 101; i++){
                Thread.sleep(90);
                hp.lblLoadingCount.setText(i + "%");
                
                if(i==20){
                    hp.lblLoading.setText("Loading Funny Puzzle...");                    
                }
                if(i==50){
                    hp.lblLoading.setText("Connecting to Database...");                    
                }
                if(i==70){
                    hp.lblLoading.setText("Connection Successful !");                    
                }
                if(i==90){
                    hp.lblLoading.setText("Lets go!");                    
                }
                if(i==101){
                    hp.dispose();
                    FormInstructionPage lpgf = new FormInstructionPage();
                    lpgf.setVisible(true);               
                }
                hp.pgbar.setValue(i);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLoadingCount;
    private javax.swing.JLabel lblmovingtext;
    private javax.swing.JProgressBar pgbar;
    // End of variables declaration//GEN-END:variables
}
